[general]
import = ["~/projects/tokyonight.nvim/extras/alacritty/tokyonight_day.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 13.0
normal = { family = "BlexMono Nerd Font", style = "Regular" }
bold = { family = "BlexMono Nerd Font", style = "Bold" }
italic = { family = "BlexMono Nerd Font", style = "Italic" }
bold_italic = { family = "BlexMono Nerd Font", style = "Bold Italic" }

[window]
dimensions = { columns = 80, lines = 25 }
decorations = "Buttonless"

[keyboard]
bindings = [{ key = "V", mods = "Control | Shift", action = "ToggleViMode" }]
#
# https://github.com/TwiggieSmallz/Default-Alacritty-TOML-Config/blob/main/alacritty.toml
