# https://github.com/TwiggieSmallz/Default-Alacritty-TOML-Config/blob/main/alacritty.toml

[general]
import = ["~/projects/alacritty-theme/themes/catppuccin_frappe.toml"]

[font]
size = 13.0

[font.normal]
family = "BlexMono Nerd Font"
style = "Regular"

[font.bold]
family = "BlexMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "BlexMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "BlexMono Nerd Font"
style = "Italic"

[window]
decorations = "None"
# Window decorations.
# Full: Borders and title bar.
# None: Neither borders nor title bar.
# Transparent (macOS only): Title bar, transparent background and title bar buttons.
# Buttonless (macOS only): Title bar, transparent background and no title bar buttons.
# Default: "Full"
